# Generated by Django 5.1.4 on 2025-01-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktwo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
