# Generated by Django 5.1.4 on 2025-01-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktwo', '0002_alter_todos_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='createdat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todos',
            name='updatedat',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
