# Generated by Django 5.1.4 on 2025-01-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktwo', '0003_alter_todos_createdat_alter_todos_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todos',
            name='updatedat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
